### ISSUE TITLE
ASK: How one would use that with a Hugo website for example?

### ISSUE THREAD

**Issue by dgomesbr** [zakhenry/embedme#13]
I'm running a bunch of code excerpts in Markdown files and I'm running issues on updating `npm` libs, they eventually broke my code. I found your repo and this is quite interesting, but due to my lack of the JS landscape in general, how would one would use this in a pipeline/bundler or CI/CD?

Could you elaborate on an example for that?

**Comment by ayazhafiz** [comment]
Are you asking how to run this on a batch of files? If so, you can make a simple bash script. For instance, say you have a dependency to `embedme` in your `package.json`:

```bash
FILES=# some definition

echo $FILES | while read -r file; do
  yarn run embed "$file"
done
```

**Comment by zakhenry** [comment]
@dgomesbr can you please explain your use case? If you have node installed you don't really need to use npm - you can use `npx` which comes bundled with node which allows you to use node based utilities in a super simple way. just `npx embedme path/to/your/documents/**/*.md`. 

@ayazhafiz note in the example I just gave that you can handle multiple files with glob matching

**Comment by dgomesbr** [comment]
Hey @zakhenry,

I have a workshop with static pages in markdown, most of those pages include at least 1-3 code excerpts. `embedme` is great, because now I can keep it outside my MD files and make sure I can compile then to see if there's any error due to library being bumped after updates.

My question is, on my `package.json` I use the following:
```
"scripts": {
        "build": "tsc && (cd ../workshop && hugo)",
        "watch": "tsc -w",
        "deploy": "npm run build && cdk deploy",
        "cdk": "cdk"
    },
```

Now what step should I add there, just ``npx embedme path/1/**/*.md`` and so on?

**Comment by zakhenry** [comment]
@dgomesbr yep that's exactly right, you'd do something along the lines of

```json
    "scripts": {
        "build": "tsc && embedme **/*.md && (cd ../workshop && hugo)",
    },
```

Note if you're using a package.json it is recommended to just install embedme as a normal package rather than using npx. All you have to do is run `npm install embedme --save-dev`

**Comment by dgomesbr** [comment]
Thanks!
