### ISSUE TITLE
Trim code when writing to file

### ISSUE THREAD

**Issue by maxime1992** [zakhenry/embedme#19]
If I've got a file `test.ts` matching the following:

```ts
interface A {
  hello: string;
}

```

(note the empty line at the end as it's usually the configuration of IDE, prettier etc)

Within a README if I've got 

![image](https://user-images.githubusercontent.com/4950209/60769271-81e85800-a0c5-11e9-831d-ba9e7200adef.png)

After running embedme it's:

![image](https://user-images.githubusercontent.com/4950209/60769279-9298ce00-a0c5-11e9-8a03-23bc5caad45d.png)

While I'd expect

![image](https://user-images.githubusercontent.com/4950209/60769288-9d536300-a0c5-11e9-99e9-02e41bf2c646.png)

I think that should be the default behaviour but if you want to let more freedom maybe add a flag to manage that case?

**Comment by maxime1992** [comment]
I also just notice that it's an issue when running prettier as:
- prettier adds an empty line at the end of a file (which can be the demo code used by embedme)
- embedme doesn't trim the code when injecting it
- prettier runs on CI and throws an errors as it wants to remove the last empty line on the code block

**Comment by zakhenry** [comment]
This issue is oddly complex - prettier's behavior differs depending on the detected code type of the code block. I'll have a think

**Comment by zakhenry** [comment]
@maxime1992 ok I've come up with a fix, it's somewhat simple as it just checks if the diff would be trailing whitespace only. Note that you have to be careful that prettier also runs on all your source files as the embedded snippets are also run through prettier. This caught me out as I was running `yarn run prettier "**/*.{js,json,json5,scss,md,ts,html}"` with yaml omitted, but the yaml embed in the fixture was being rewritten, causing a diff and the tests to fail.

**Comment by maxime1992** [comment]
Nice one :raised_hands: I'll give a try asap :)
