### ISSUE TITLE
Bug introduced on #22: ALL changes result in "Changes are trailing whitespace only, ignoring"

### ISSUE THREAD

**Issue by donpedro** [zakhenry/embedme#24]
#22 appears to have introduced a bug in my use case. I am not using prettier, just running out of the box.

[This code](https://github.com/zakhenry/embedme/pull/22/commits/0ab89a52ff167ab5ac6696f954ef04850a7e6d7a#diff-567d020579ff0cbc46c3ecdff2804fefR328):
```
  if (replacement.substr(-3).trimRight() === substr.substr(-3).trimRight()) {
    log({ returnSnippet: substr }, chalk.gray(`Changes are trailing whitespace only, ignoring`));
    return substr;
  }
```

ALWAYS returns true, when it compares the existing block:
````
```js
// gulpfile.js
``` 
````
With the replacement:
````
```js
// gulpfile.js
"use strict";

const abc = 123;
...
``` 
````

It's comparing the trailing fences in every case, thus any change is considered "trailing whitespace".

**Comment by ayazhafiz** [comment]
I just encountered this bug too. Looks like
https://github.com/zakhenry/embedme/blob/a92e9e49341f2307b71a1ce2e403e2bafbb81516/src/embedme.lib.ts#L330
should use `slice(0, -3)` instead.

**Comment by zakhenry** [comment]
Sorry about that @donpedro, @ayazhafiz has kindly fixed this and a fix will be shipped shortly
