### ISSUE TITLE
Support Pandoc fenced code blocks

### ISSUE THREAD

**Issue by nlohmann** [zakhenry/embedme#30]
In [Pandoc](https://pandoc.org), code blocks may not just start with the extension like

<pre>
```json
{"key": true}
```
</pre>

but may also have more information in the line after the starting backticks (see https://pandoc.org/MANUAL.html#fenced-code-blocks):

<pre>
```{.json caption="Some JSON file"}
{"key": true}
```
</pre>

Unfortunately, code like this is currently rejected with a message like

```
Unsupported file extension [{.json], supported extensions are txt, ts, js, scss, rust, java, cpp, c, html, xml, md, yaml, json, json5, py, bash, sh, go, objectivec, php, cs, swift, rb, kotlin, scala, cr, puml, mermaid, skipping code block
```

I would really love to use embedme together with Pandoc!

**Comment by zakhenry** [comment]
Hey @nlohmann this is an interesting issue, I'm not sure how best to support it in a generic fashion however I could probably alter the priority of strategies so that the comment embed style takes precedence. For example:

    

    ```{.json caption="Some JSON file"}
    {"key": true}
    ```


Would this suit your needs?

**Comment by zakhenry** [comment]
I thought about it a little more and I think it is sensible to have the comment strategy always take precedence so I've gone ahead and implemented that so the example given in my previous comment will now work on the latest version.

Let me know if that is sufficient or if further complexity might be warranted.

**Comment by nlohmann** [comment]
Thanks a lot! The latest version works as expected! Thanks so much for the quick response!

**Comment by zakhenry** [comment]
No problem, I'm glad it works :)
