### ISSUE TITLE
Comments are not detected when CRLF is used instead of LF

### ISSUE THREAD

**Issue by thewalla07** [zakhenry/embedme#36]
This is just a simple compatibility issue, but it took me a while to figure out. 99% of my files had LF endings, except for my README.md, and I couldn't figure out why embedme wasn't recognizing my comments. My comments were structured identically to those found in the first example in https://github.com/zakhenry/embedme/blob/master/README.md#usage

After changing to LF instead of CRLF it works fine.

**Comment by thewalla07** [comment]
I would like to submit a pull request to fix this, but I can't seem to figure out how to test my local changes (not too familiar with npm)

**Comment by zakhenry** [comment]
@thewalla07 that would be much appreciated! For running locally I'd recommend just following the same steps that travis CI does - https://github.com/zakhenry/embedme/blob/master/.travis.yml#L9-L19

Also the tests are run once you raise a pull request so you could just let the CI system do the testing for you. If you raise a PR I'd be happy to help getting the test passing with you

**Comment by thewalla07** [comment]
Perfect, sounds good. I was having some issues with trying to get it going with npm, I'll try the steps Travis takes
