### ISSUE TITLE
[Request] add support for .tsx files

### ISSUE THREAD

**Issue by jsamr** [zakhenry/embedme#62]
For example, I cannot set code block syntax to `tsx`, which is unfortunate:

README.MD:
<pre>
```tsx
// source.tsx
```
</pre>

```bash
$ npx embedme README.MD
README.MD#L1-3 Unsupported file extension [tsx], supported extensions are txt, ts, js, re, scss, rust, java, cpp, c, html, xml, md, yaml, json, json5, py, bash, sh, go, objectivec, php, cs, swift, rb, kotlin, scala, cr, puml, mermaid, cmake, proto, sql, hs, ino, skipping code block
```

**Comment by zakhenry** [comment]
Hi @jsamr this just needs another case for TSX, I'll rename this issue accordingly. If you want to take a crack at an PR yourself, please go ahead - most of the recent PRs are adding support for more languages so it should be easy enough to follow the pattern
