### ISSUE TITLE
Return error code when file is renamed or moved

### ISSUE THREAD

**Issue by jci-aws** [zakhenry/embedme#93]
When using the `--verify` flag, if a file being referenced is renamed or moved, `embedme` won't return a non-zero error code. This would be helpful in CI, to ensure that the code being referenced actually exists.

_index.ts_
```ts
function add(x: number, y: number): number {
  return x + y
}
```

_README.md_
`````
```ts
// ./index.ts

function add(x: number, y: number): number {
  return x + y
}
```
`````

```bash
mv index.ts add.ts # rename index.ts to add.ts
npx embedme README.md --verify # run embedme with --verify
echo $? # get return code
```

### Current Behavior

```bash
Verifying...
  Analysing README.md...
   README.md#L1-L7 Found filename ./index.ts in comment in first line, but file does not exist at /embedme-test/index.ts!
0
```

### Desired Behavior

```bash
Verifying...
  Analysing README.md...
   README.md#L1-L7 Found filename ./index.ts in comment in first line, but file does not exist at /embedme-test/index.ts!
1
```

I'm free to open a PR if you're open to it.

**Comment by zakhenry** [comment]
reopening until this is actually released

**Comment by zakhenry** [comment]
cool the release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/embedme)
- [GitHub release](https://github.com/zakhenry/embedme/releases/tag/v1.22.1)
